server {
    listen 80;
    
    # Onde estão os arquivos do site
    root /usr/share/nginx/html;
    index index.html;

    # O Pulo do Gato:
    # Tenta achar o arquivo ($uri), se não achar, manda pro index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}