# BLOCO DA EMPRESA (kubelabs.online)
server {
    listen 80;
    server_name kubelabs.online www.kubelabs.online;

    location / {
        proxy_pass http://kubelabs_landing:80; # Manda para o container da Landing
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# BLOCO DO JOGO (digimon.kubelabs.online)
server {
    listen 80;
    server_name digimon.kubelabs.online;

    location / {
        proxy_pass http://digimon_frontend:80; # Manda para o container do Jogo
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}