server {
    listen 80;
    server_name localhost;

    # Onde os arquivos do build do React ficam no container
    root /usr/share/nginx/html;
    index index.html;

    # Configuração essencial para Single Page Applications (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos (imagens, css, js)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires -1;
        add_header Cache-Control "public, no-transform";
    }
}