services:
  # --- O BANCO DE DADOS (Inalterado) ---
  db:
    image: mysql:8.0
    container_name: digimon_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Luk3skywalker!
      MYSQL_DATABASE: digimonomega
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # --- O BACKEND API (Inalterado) ---
  backend:
    build: ./backend
    container_name: digimon_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/public/assets:/app/public/assets

  # --- O JOGO (Mudou: Perdeu a porta 80 pública) ---
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://digimon.kubelabs.online
    container_name: digimon_frontend
    restart: always
    expose:
      - "80" # Apenas exposto internamente para o Proxy
    depends_on:
      - backend

  # --- O PORTEIRO (HTTPS + Proxy reverso) ---
  proxy:
    image: caddy:2-alpine
    container_name: main_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

volumes:
  db_data:
  caddy_data:
  caddy_config:
