services:
  # --- O BANCO DE DADOS (Inalterado) ---
  db:
    image: mysql:8.0
    container_name: digimon_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Luk3skywalker!
      MYSQL_DATABASE: digimonomega
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # --- O BACKEND API (Inalterado) ---
  backend:
    build: ./backend
    container_name: digimon_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  # --- O JOGO (Mudou: Perdeu a porta 80 pública) ---
  frontend:
    build: ./frontend
    container_name: digimon_frontend
    restart: always
    expose:
      - "80" # Apenas exposto internamente para o Proxy
    depends_on:
      - backend

  # --- A LANDING PAGE (Novo) ---
  landing:
    build: ./landing-page
    container_name: kubelabs_landing
    restart: always
    expose:
      - "80" # Apenas exposto internamente para o Proxy

  # --- O PORTEIRO (Novo Dono da Porta 80) ---
  nginx_proxy:
    image: nginx:alpine
    container_name: main_proxy
    restart: always
    ports:
      - "80:80" # Ele recebe todo o tráfego da internet
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Sua lista de regras
    depends_on:
      - frontend
      - landing

volumes:
  db_data: