# BLOCO DA EMPRESA (kubelabs.online)
server {
    listen 80 default_server;
    server_name kubelabs.online www.kubelabs.online;

    location / {
        # Manda para o container da Landing Page
        proxy_pass http://landing:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# BLOCO DO JOGO (digimon.kubelabs.online)
server {
    listen 80;
    server_name digimon.kubelabs.online;

    location / {
        # Manda para o container do Jogo
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}